// @ts-check
import test from 'ava';
import { Component } from '../../src/component/component.js';
import { Config } from '../../src/component/config.js';
import { html, unsafeHTML } from '../../src/utils/utils.js';

/**
 * Test for SID-based component lookup.
 * Verifies that the recursive search correctly identifies children
 * based on their hierarchical string identifiers.
 */
test('Component: getComponentBySid finds nested children recursively', t => {
    const parent = new Component({ sid: 'root' });
    const child = new Component();
    const grandchild = new Component();

    // Setup a nested structure using slots
    parent.setLayout(() => html`<div data-slot="main"></div>`);
    parent.addToSlot('main', child);

    child.setLayout(() => html`<div data-slot="sub"></div>`);
    child.addToSlot('sub', grandchild);

    // Expected SIDs generated by #recursiveUpdateSid:
    // child -> root.main.0
    // grandchild -> root.main.0.sub.0
    const targetSid = 'root.main.0.sub.0';

    t.is(parent.getComponentBySid('root'), parent, 'Should identify itself by SID');
    t.is(parent.getComponentBySid('root.main.0'), child, 'Should find direct child in slot');
    t.is(parent.getComponentBySid(targetSid), grandchild, 'Should find deep grandchild');
    t.is(
        parent.getComponentBySid('invalid.path'),
        null,
        'Should return null for non-existent SIDs'
    );
});

/**
 * Test for manual hydration data retrieval.
 * Ensures that components can pull their specific server-state
 * from the global Config manifest at any time.
 */
test('Component: getHydrationData retrieves state from Config manifest', t => {
    const sid = 'test-id-456';
    const mockState = { theme: 'dark', version: 2 };

    // Mocking the global hydration data provider in Config
    const originalGetter = Config.getHydrationData;
    Config.getHydrationData = id => (id === sid ? mockState : null);

    const comp = new Component({ sid });
    t.deepEqual(comp.getHydrationData(), mockState, 'Should return matching data from manifest');

    const noSidComp = new Component();
    t.is(noSidComp.getHydrationData(), null, 'Should return null if component has no SID');

    // Restore original Config method
    Config.getHydrationData = originalGetter;
});

/**
 * Test for lifecycle cleanup.
 * Verifies that elements marked for removal are properly purged from the DOM
 * when the component is unmounted.
 */
test('Component: removeOnUnmount cleans up manual DOM elements', t => {
    const container = document.createElement('div');
    const comp = new Component();
    comp.setLayout(() => html`<div class="root"></div>`);
    comp.mount(container);

    const extraEl = document.createElement('span');
    document.body.appendChild(extraEl); // Attached elsewhere

    comp.removeOnUnmount(extraEl);
    t.truthy(document.body.contains(extraEl), 'Element should exist before unmount');

    comp.unmount();
    t.falsy(document.body.contains(extraEl), 'Element should be removed after unmount');
});

/**
 * Test for queryLocal boundary enforcement.
 * Ensures that queryLocal does not "leak" into nested child components.
 */
test('Component: queryLocal respects component scope boundaries', t => {
    const parent = new Component();
    const child = new Component();

    // Parent has one <span>, child has another <span>
    parent.setLayout(
        () =>
            html`<div>
                <span>Parent Span</span>
                <div data-slot="content"></div>
            </div>`
    );
    child.setLayout(() => html`<section><span>Child Span</span></section>`);

    parent.mount(document.createElement('div'));
    parent.addToSlot('content', child);

    const spans = parent.queryLocal('span');
    t.is(spans.length, 1, 'Should only find the span belonging to the parent');
    t.is(spans[0].textContent, 'Parent Span');
});

// --- Lifecycle & Mounting ---

test('Component: mount logic with different modes', t => {
    const container = document.createElement('div');
    container.innerHTML = '<div id="existing"></div>';

    const comp = new Component();
    comp.setLayout(() => html`<div class="root">New</div>`);

    // Test "append" mode
    comp.mount(container, 'append');
    t.is(container.children.length, 2, 'Should append as second child');

    // Test "replace" mode
    const comp2 = new Component();
    comp2.setLayout(() => html`<div class="root-2">Replaced</div>`);
    comp2.mount(container, 'replace');
    t.is(container.children.length, 1, 'Should clear container and add one child');
    t.truthy(container.querySelector('.root-2'));
});

// --- Collapsing & Expansion ---

test('Component: collapse and expand state tracking', t => {
    // FIX: Append the container to document.body so isConnected becomes true
    const container = document.createElement('div');
    document.body.appendChild(container);

    const comp = new Component();
    comp.setLayout(() => html`<div class="content">Visible</div>`);

    // Initial mount
    comp.mount(container, 'append');
    t.true(comp.isConnected, 'Should be connected initially');

    // Collapse
    comp.collapse();
    t.false(comp.isConnected, 'Should be disconnected after collapse');
    t.is(container.querySelector('.content'), null);

    // Expand
    comp.expand();
    // Now this will pass because container.isConnected is true
    t.true(comp.isConnected, 'Should be reconnected');
    t.false(comp.isCollapsed, 'isCollapsed flag should be false');
    t.truthy(container.querySelector('.content'));

    // Cleanup
    container.remove();
});

// --- Hydration & Teleports (Addressing lines 751-791) ---

test('Component: hydration and teleport synchronization', t => {
    // 1. Simulate SSR HTML structure
    const serverId = 'ssr-123';
    document.body.innerHTML = `
        <div id="app" data-sid="${serverId}">
            <div data-slot="main"></div>
        </div>
        <div id="portal" data-parent-sid="${serverId}" data-component-teleport="modal">
            Existing Teleport
        </div>
    `;

    const appContainer = document.getElementById('app');

    // 2. Define component with matching Teleport
    class HydratedComp extends Component {
        constructor(opts) {
            super(opts);
            this.layout = () => html`<div>Main</div>`;
            this.teleports = {
                modal: {
                    layout: () => html`<div class="modal">New Modal</div>`,
                    target: '#portal',
                },
            };
        }
    }

    const comp = new HydratedComp({ sid: serverId });

    // 3. Perform Hydration
    // This triggers #applyHydration and #hydrateTeleports
    comp.mount(appContainer, 'hydrate');

    t.is(
        comp.instanceId,
        appContainer.getAttribute('data-component-root'),
        'Should claim existing root'
    );
    t.is(appContainer.getAttribute('data-sid'), null, 'Should clean up data-sid attribute');

    // Check Teleport Hydration
    const teleported = document.getElementById('portal');
    t.is(
        teleported.getAttribute('data-component-root'),
        comp.instanceId,
        'Should claim existing teleport node'
    );
    t.is(
        teleported.getAttribute('data-parent-sid'),
        null,
        'Should remove parent-sid from teleport'
    );

    comp.unmount();
});

// --- Recursive SID Updates (Addressing lines 815-830) ---

test('Component: recursive SID updates when adding to slots', t => {
    const parent = new Component({ sid: 'P' });
    const child = new Component(); // No SID yet
    const grandchild = new Component();

    parent.setLayout(() => html`<div data-slot="s1"></div>`);
    child.setLayout(() => html`<div data-slot="s2"></div>`);

    // Attach grandchild to child first
    child.addToSlot('s2', grandchild);

    // Attach child to parent (triggers #recursiveUpdateSid)
    parent.addToSlot('s1', child);

    t.is(child.$internals.sid, 'P.s1.0', 'Child should receive calculated SID');
    t.is(grandchild.$internals.sid, 'P.s1.0.s2.0', 'Grandchild should receive deep calculated SID');
});

// --- Error Boundaries ---

test('Component: throws error when mounting to invalid target', t => {
    const comp = new Component();
    // @ts-ignore
    t.throws(() => comp.mount(null), { message: /Target element not found/ });
    // @ts-ignore
    t.throws(() => comp.mount(document.createElement('div'), 'invalid-mode'), {
        message: /Invalid mount mode/,
    });
});

/**
 * Test for local DOM queries with selectors.
 * Covers filtering logic inside the scoped DOM walker.
 */
test('Component: queryLocal with CSS selectors', t => {
    const comp = new Component();
    comp.setLayout(
        () => html`
            <div>
                <button class="active">Yes</button>
                <button class="hidden">No</button>
            </div>
        `
    );
    comp.mount(document.createElement('div'));

    const activeBtns = comp.queryLocal('button', '.active');
    t.is(activeBtns.length, 1, 'Should filter by class selector');
    t.is(activeBtns[0].textContent, 'Yes');
});

/**
 * Test for SID lookup optimization.
 * Covers the early return when a SID branch does not match.
 */
test('Component: getComponentBySid prefix optimization', t => {
    const comp = new Component({ sid: 'app.header' });
    // This should return null immediately without checking slots
    const result = comp.getComponentBySid('app.footer.btn');
    t.is(result, null, 'Should skip search if SID prefix does not match');
});

/**
 * Test for Full Hydration and Teleport Claiming.
 * This covers the complex logic in the 700-800 line range where
 * the client "takes over" DOM nodes created by the server.
 */
test('Component: full hydration cycle with teleports', t => {
    const sid = 'ssr-root-001';

    // 1. Setup Mock Server HTML
    document.body.innerHTML = `
        <div id="container">
            <div id="ssr-root" data-sid="${sid}">
                <div data-ref="title">Server Title</div>
                <div data-slot="content"></div>
            </div>
            <div id="ssr-modal" data-parent-sid="${sid}" data-component-teleport="msg">
                Server Message
            </div>
        </div>
    `;

    const rootEl = document.getElementById('ssr-root');
    const modalEl = document.getElementById('ssr-modal');

    // 2. Define the Component
    class MyApp extends Component {
        constructor(opts) {
            super(opts);
            this.layout = () =>
                html`<div>
                    <h1 data-ref="title"></h1>
                    <div data-slot="content"></div>
                </div>`;
            this.teleports = {
                msg: {
                    layout: () => html`<div>Message</div>`,
                    target: document.body,
                },
            };
        }
    }

    const app = new MyApp({ sid });

    // 3. Trigger Hydration (Hits lines 755-795)
    app.mount(rootEl, 'hydrate');

    // Verification
    t.is(app.isConnected, true, 'Component should be connected via hydration');
    t.is(rootEl.getAttribute('data-component-root'), app.instanceId, 'Root should be claimed');
    t.is(modalEl.getAttribute('data-component-root'), app.instanceId, 'Teleport should be claimed');
    t.is(modalEl.getAttribute('data-parent-sid'), null, 'SSR markers should be removed');

    // 4. Test queryLocal with filter (Hits lines 693-712)
    const title = app.queryLocal('div', '[data-ref="title"]');
    t.is(title.length, 1, 'queryLocal should support CSS filtering');

    app.unmount();
});

/**
 * Test for immediate mounting in slots.
 * Ensures that if a parent is already in the DOM, adding a child
 * to its slot triggers an immediate mount for that child.
 */
test('Component: immediate mount when adding to connected parent', t => {
    const parent = new Component();
    // Ensure the slot exists in the layout
    parent.setLayout(() => html`<div data-slot="main"></div>`);

    // Mount parent to the real DOM
    parent.mount(document.body, 'append');
    t.true(parent.isConnected, 'Parent must be connected first');

    const child = new Component();
    child.setLayout(() => html`<span class="child-node">Child</span>`);

    // ACT: Add child to an already connected parent
    parent.addToSlot('main', child);

    // ASSERT: Child should be connected immediately
    t.true(child.isConnected, 'Child should be mounted immediately if parent is connected');

    const childElement = document.body.querySelector('.child-node');
    t.truthy(childElement, 'Child DOM node should be present in document.body');

    // Cleanup
    parent.unmount();
});

/**
 * Test for local queries with filtering.
 * Covers the filtering branch of queryLocal.
 */
test('Component: queryLocal filtering logic', t => {
    const comp = new Component();
    comp.setLayout(
        () => html`
            <ul>
                <li class="item active">1</li>
                <li class="item">2</li>
            </ul>
        `
    );
    comp.mount(document.createElement('div'));

    const all = comp.queryLocal('li');
    const filtered = comp.queryLocal('li', '.active');

    t.is(all.length, 2);
    t.is(filtered.length, 1);
    t.is(filtered[0].textContent, '1');
});

/**
 * Test for deep SID propagation.
 * Covers the #recursiveUpdateSid method for nested structures.
 */
test('Component: deep recursive SID update', t => {
    const p = new Component({ sid: 'root' });
    const c = new Component();
    const g = new Component();

    p.setLayout(() => html`<div data-slot="s1"></div>`);
    c.setLayout(() => html`<div data-slot="s2"></div>`);

    p.addToSlot('s1', c);
    c.addToSlot('s2', g);

    t.is(g.$internals.sid, 'root.s1.0.s2.0', 'Grandchild should have correct nested SID');
});

/**
 * Test for thorough cleanup during unmount.
 * Covers the teardown of teleports and disconnection logic.
 */
test('Component: unmount cleans up everything', t => {
    const container = document.createElement('div');
    document.body.appendChild(container);

    const comp = new Component();

    // FIX: Define the main layout so mount() doesn't throw
    comp.setLayout(() => html`<div class="main-shell"></div>`);

    comp.teleports = {
        popup: {
            layout: () => html`<div id="pop">Teleport Content</div>`,
            target: document.body,
        },
    };

    // This triggers #render, #mountTeleports, and #connect
    comp.mount(container);
    t.truthy(document.getElementById('pop'), 'Teleport should exist in document.body');

    // ACT: Perform unmount
    comp.unmount();

    // ASSERT: Check that everything is purged
    t.falsy(document.getElementById('pop'), 'Teleport should be removed from body');
    t.falsy(container.querySelector('.main-shell'), 'Main content should be removed');
    t.false(comp.isConnected, 'Component state should be disconnected');

    container.remove();
});

test('Component: mount supports prepend mode', t => {
    const container = document.createElement('div');
    container.innerHTML = '<div id="existing">Existing</div>';

    const comp = new Component();
    comp.setLayout(() => html`<div id="new">New</div>`);

    comp.mount(container, 'prepend');

    t.is(container.firstElementChild.id, 'new', 'New element should be the first child');
    t.is(
        container.lastElementChild.id,
        'existing',
        'Old element should be moved to second position'
    );
});

/**
 * Test for static layout caching.
 * Covers the #render logic that uses template cloning for performance.
 */
test('Component: static layout caching via cloneNode', t => {
    const comp = new Component();
    // Enable cloning and provide a static string layout
    comp.$internals.cloneTemplateOnRender = true;
    comp.setLayout('<div class="static-node">Static Content</div>');

    const container = document.createElement('div');

    // First render: creates the template
    comp.mount(container, 'append');
    const firstNode = comp.getRootNode();
    comp.unmount();

    // Second render: clones from the cached template
    comp.mount(container, 'append');
    const secondNode = comp.getRootNode();

    t.not(firstNode, secondNode, 'Nodes must be different instances (clones)');
    t.is(secondNode.className, 'static-node');
    t.is(secondNode.textContent, 'Static Content');
});

/**
 * Test for immediate mounting in slots.
 * Ensures that if a parent is already connected, adding a child
 * to its slot triggers an immediate mount.
 */
test('Component: immediate mount in active parent', t => {
    const parent = new Component();
    parent.setLayout(() => html`<div data-slot="main"></div>`);
    parent.mount(document.body); // Parent is now connected

    const child = new Component();
    child.setLayout(() => html`<span class="child">Child</span>`);

    // ACT: Add to active parent
    parent.addToSlot('main', child);

    t.true(child.isConnected, 'Child should be connected immediately');
    t.truthy(document.body.querySelector('.child'), 'Child should exist in DOM');

    parent.unmount();
});

/**
 * Test for recursive SID propagation.
 * Covers #recursiveUpdateSid when moving a branch to a new slot.
 */
test('Component: deep recursive SID update on move', t => {
    const root = new Component({ sid: 'app' });
    const branch = new Component();
    const leaf = new Component();

    root.setLayout(() => html`<div data-slot="slotA"></div>`);
    branch.setLayout(() => html`<div data-slot="slotB"></div>`);
    leaf.setLayout(() => html`<span>Leaf</span>`);

    // Build tree: app -> slotA.0 (branch) -> slotB.0 (leaf)
    branch.addToSlot('slotB', leaf);
    root.addToSlot('slotA', branch);

    t.is(leaf.$internals.sid, 'app.slotA.0.slotB.0', 'Initial deep SID should be correct');

    // MOVE: Move branch to a different slot in root
    root.setLayout(() => html`<div data-slot="newSlot"></div>`);
    root.addToSlot('newSlot', branch);

    t.is(
        leaf.$internals.sid,
        'app.newSlot.0.slotB.0',
        'Deep SID should update recursively after parent move'
    );
});

/**
 * Test for internal validation and error boundaries.
 * Covers throw statements for invalid mount targets and missing layouts.
 */
test('Component: validation and hydration errors', t => {
    const comp = new Component();
    const container = document.createElement('div');

    // 1. Missing Layout Error
    t.throws(() => comp.mount(container), { message: /Layout is not defined/ });

    // 2. Invalid Mount Target (Type Check)
    comp.setLayout('<div></div>');
    // @ts-ignore
    t.throws(() => comp.mount(null), { message: /Target element not found/ });

    // 3. Invalid Mount Mode
    // @ts-expect-error
    t.throws(() => comp.mount(container, 'invalid_mode'), { message: /Invalid mount mode/ });

    // 4. Hydration without SID
    t.throws(() => comp.mount(container, 'hydrate'), {
        message: /Hydration failed: No SID assigned/,
    });
});

/**
 * Test for teleport removal during unmount.
 * Covers the cleanup loop in the unmount lifecycle.
 */
test('Component: cleans up teleports and manual elements', t => {
    const comp = new Component();
    comp.setLayout('<div>Main</div>');
    comp.teleports = {
        overlay: { layout: () => html`<div id="tel-node"></div>`, target: document.body },
    };

    comp.mount(document.createElement('div'));
    const manualEl = document.createElement('div');
    document.body.appendChild(manualEl);
    comp.removeOnUnmount(manualEl);

    t.truthy(document.getElementById('tel-node'), 'Teleport should exist');
    t.truthy(document.body.contains(manualEl), 'Manual element should exist');

    comp.unmount();

    t.falsy(document.getElementById('tel-node'), 'Teleport should be removed');
    t.falsy(document.body.contains(manualEl), 'Manual element should be removed');
});

/**
 * Test for static template cloning.
 * Targets lines 506-554 in component.js.
 */
test('Component: static template clone branch', t => {
    const comp = new Component();
    comp.setLayout(' <div class="static">Static</div> '); // Leading space hits .trim()
    comp.$internals.cloneTemplateOnRender = true;

    const container = document.createElement('div');

    // First mount creates cache
    comp.mount(container);
    const node1 = comp.getRootNode();
    comp.unmount();

    // Second mount uses cache
    comp.mount(container);
    const node2 = comp.getRootNode();

    t.is(node2.className, 'static');
    t.not(node1, node2, 'Nodes should be different instances from the same template');
});

/**
 * Test for Component Disconnection Logic.
 * Targets lines 766-793 in component.js.
 */
test('Component: aborts signals and cleans up listeners on unmount', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');

    const container = document.createElement('div');
    comp.mount(container);

    // Get a reference to the controller before it's replaced or aborted
    const controller = comp.$internals.disconnectController;
    let aborted = false;
    controller.signal.addEventListener('abort', () => {
        aborted = true;
    });

    // Trigger the unmount/disconnect logic
    comp.unmount();

    t.true(aborted, 'The disconnect AbortSignal should be aborted on unmount');
    t.true(
        comp.$internals.disconnectController.signal.aborted,
        'Internal signal state should be updated'
    );
});

test('Component: re-mounting and cleanup', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');
    const container = document.createElement('div');

    comp.mount(container);
    comp.unmount();

    // Targets 858-860: Attempting to unmount an already unmounted component
    t.notThrows(() => comp.unmount(), 'Should be idempotent');
});

/**
 * Test for getComponentBySid.
 * Ensures hierarchical SIDs are searched correctly.
 */
test('Component: getComponentBySid performs deep search and returns null if not found', t => {
    const parent = new Component({ sid: 'root' });
    // Use a simpler layout to ensure the slot is recognized
    parent.setLayout('<div data-slot="content"></div>');

    const child = new Component();
    child.setLayout('<span>Child</span>');

    parent.addToSlot('content', child);

    const parentSid = parent.$internals.sid;
    const childSid = child.$internals.sid;

    // Verify SIDs exist for the search logic to work
    t.is(parentSid, 'root', 'Parent should have the manually assigned root SID');
    t.truthy(childSid, 'Child should have an inherited SID');

    // 3. Target: Quick check (is it me?)
    t.is(parent.getComponentBySid(parentSid), parent, 'Should return itself if SID matches');

    // 4. Target: Optimization check (Optimization branch line)
    // Providing a SID that doesn't start with "root."
    t.is(
        parent.getComponentBySid('other.123'),
        null,
        'Should return null if prefix does not match'
    );

    // 5. Target: Successful deep search (Recursive branch)
    const found = parent.getComponentBySid(childSid);
    t.is(found, child, 'Should find the nested child by recursively searching slots');

    // 6. Target: FINAL NULL RETURN (Bottom of the function)
    // Starts with "root." but the rest doesn't exist
    const fakeChildSid = 'root.999';
    t.is(
        parent.getComponentBySid(fakeChildSid),
        null,
        'Should return null after checking all slots'
    );
});

test('Component: hydration flow should restore metadata when available', t => {
    const testMetadata = { theme: 'dark' };

    // Mock the global config to provide hydration data for a specific SID
    const originalGet = Config.getHydrationData;
    Config.getHydrationData = sid => (sid === '0.1' ? testMetadata : null);

    const comp = new Component({ sid: '0.1' });
    comp.setLayout('<div></div>');

    let capturedData = null;
    comp.on('restore', data => {
        capturedData = data;
    });

    // Create a container and trigger the hydration flow
    const container = document.createElement('div');
    container.setAttribute('data-sid', '0.1');

    // This call internally triggers #applyHydration
    comp.mount(container, 'hydrate');

    t.true(comp.$internals.isHydrated, 'Component should be marked as hydrated internally');
    t.deepEqual(capturedData, testMetadata, 'Restore event should receive data from Config');

    Config.getHydrationData = originalGet;
});

test('Component: hydration should fallback to mounting teleports if they are missing in DOM', t => {
    const container = document.createElement('div');
    container.setAttribute('data-sid', 'app.1');
    document.body.appendChild(container);

    // Define a component with a teleport
    class TeleportComp extends Component {
        // @ts-ignore
        teleports = {
            modal: { target: 'body', layout: () => '<div id="fallback-node">Content</div>' },
        };
        render() {
            return '<div>Main</div>';
        }
    }

    const comp = new TeleportComp({ sid: 'app.1' });
    comp.setLayout('<div></div>');

    // Hydrating into a DOM that doesn't have the teleport node
    // forces the execution of the 'else' branch in #hydrateTeleports
    comp.mount(container, 'hydrate');

    const fallbackNode = document.getElementById('fallback-node');
    t.truthy(fallbackNode, 'Teleport node should be created via fallback mount logic');

    // Cleanup
    document.body.removeChild(container);
    fallbackNode.remove();
});

test('Component: mount should throw error when target element is not found', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');
    // We try to mount to a non-existent CSS selector
    const error = t.throws(
        () => {
            comp.mount('#this-id-does-not-exist');
        },
        { instanceOf: Error }
    );

    t.regex(error.message, /Target element not found/, 'Should throw descriptive error');
});

test('Component: should resolve mount target from a function', t => {
    const dynamicTarget = document.createElement('section');
    document.body.appendChild(dynamicTarget);

    const comp = new Component();
    comp.setLayout('<div></div>');
    // Mount using a function that returns an element
    // This internally hits the "typeof target === 'function'" branch in #insertToDOM
    comp.mount(() => dynamicTarget);

    t.is(
        dynamicTarget.children.length,
        1,
        'Should mount into the element returned by the function'
    );

    document.body.removeChild(dynamicTarget);
});

test('Component: mount should support string selectors as containers', t => {
    // Setup DOM
    const div = document.createElement('div');
    div.id = 'app-root';
    document.body.appendChild(div);

    const comp = new Component();
    comp.setLayout('<div></div>');
    // Resolve via string selector
    comp.mount('#app-root');

    t.is(div.children.length, 1, 'Component should be mounted into element found by ID');
    document.body.removeChild(div);
});

test('Component: mount should support functions as containers', t => {
    const div = document.createElement('div');
    const comp = new Component();
    comp.setLayout('<div></div>');
    // Resolve via provider function
    comp.mount(() => div);

    t.is(div.children.length, 1, 'Component should be mounted into element returned by function');
});

test('Component: mount should throw when selector returns nothing', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');
    // Test failure branch
    const error = t.throws(
        () => {
            comp.mount('#non-existent-selector-123');
        },
        { instanceOf: Error }
    );

    t.regex(
        error.message,
        /\[Mounting Error\] Target element not found/,
        'Should provide a helpful error message'
    );
});

test('Component: getRootNode should throw error if component is not mounted', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');

    // Testing the error branch: accessing root before it exists
    const error = t.throws(
        () => {
            comp.getRootNode();
        },
        { instanceOf: Error }
    );

    t.is(
        error.message,
        'Component is not connected to the DOM',
        'Should provide the correct error message'
    );
});

test('Component: queryLocal should throw error if component is not mounted', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');

    // queryLocal internally calls the private #getElementsByTagName
    // Testing the error branch: querying DOM before connection
    const error = t.throws(
        () => {
            comp.queryLocal('div');
        },
        { instanceOf: Error }
    );

    t.is(
        error.message,
        'Component is not connected to the DOM',
        'Should block DOM queries on unmounted components'
    );
});

test('Component: #handleMove should support prepend strategy for connected components', t => {
    // Create first container and mount
    const container1 = document.createElement('div');
    const comp = new Component();
    comp.setLayout('<div></div>');
    comp.mount(container1);

    // Create second container with an existing child
    const container2 = document.createElement('div');
    const existingChild = document.createElement('span');
    container2.appendChild(existingChild);

    // Move component to container2 using prepend
    // This triggers #handleMove internally
    comp.mount(container2, 'prepend');

    t.is(
        container2.firstChild,
        comp.getRootNode(),
        'The component should be the first child after prepend'
    );
    t.is(
        container2.children.length,
        2,
        'Container should contain both the component and the existing child'
    );
    t.is(comp.$internals.mountMode, 'prepend', 'Internal mountMode should be updated to prepend');
});

test('Component: rerender should cycle the component through collapse and expand', t => {
    const container = document.createElement('div');
    document.body.appendChild(container);

    class LifecycleComp extends Component {
        // Using a counter to ensure the output could be different
        count = 0;
        layout = () => {
            this.count++;
            return `<div>Render #${this.count}</div>`;
        };
    }

    const comp = new LifecycleComp();
    comp.mount(container);

    const initialRoot = comp.getRootNode();
    t.is(initialRoot.textContent, 'Render #1');

    // Trigger rerender: this calls collapse() then expand()
    comp.rerender();

    const newRoot = comp.getRootNode();

    // Assertions
    t.not(initialRoot, newRoot, 'A new DOM root instance should be created');
    t.is(newRoot.textContent, 'Render #2', 'The content should reflect the second render call');
    t.is(container.firstChild, newRoot, 'The new root should be present in the container');
    t.false(initialRoot.isConnected, 'The old root should be detached from the document');

    document.body.removeChild(container);
});

test('Component: #handleMove should emit move event with target container', t => {
    const container1 = document.createElement('div');
    const container2 = document.createElement('section');

    const comp = new Component();
    comp.setLayout('<div></div>');
    comp.mount(container1);

    let eventPayload = null;
    comp.on('move', data => {
        eventPayload = data;
    });

    comp.mount(container2, 'append');

    t.truthy(eventPayload, 'Move event should be fired');

    // @ts-ignore
    t.is(eventPayload.to, container2, 'Event payload should contain the new target container');
});

test('Component: expandForce should recursively expand all ancestors using addToSlot', t => {
    const container = document.createElement('div');
    document.body.appendChild(container);

    class Parent extends Component {
        layout = '<div><div data-slot="childSlot"></div></div>';
    }
    const parentComp = new Parent();
    parentComp.mount(container);

    const childComp = new Component();
    childComp.setLayout('<span>Child</span>');
    parentComp.addToSlot('childSlot', childComp);

    // Collapse parent
    parentComp.collapse();
    t.false(parentComp.isConnected);

    // Act: Force expansion
    childComp.expandForce();

    // Assert
    t.true(parentComp.isConnected, 'Parent should be expanded');
    t.true(childComp.isConnected, 'Child should be expanded');

    const freshSlotElement = parentComp.slotManager.getSlotElement('childSlot');

    t.is(
        childComp.getRootNode().parentElement,
        freshSlotElement,
        'Child should be inside the NEWLY rendered slot element'
    );

    document.body.removeChild(container);
});

test('Component: getSlotNames should return all slot names defined in the layout', t => {
    class MultiSlotComp extends Component {
        // Defining a layout with multiple named slots
        layout = `
            <div>
                <aside data-slot="sidebar"></aside>
                <main data-slot="content"></main>
                <footer data-slot="footer"></footer>
            </div>
        `;
    }

    const comp = new MultiSlotComp();

    // We must mount the component (or trigger render)
    // so the SlotManager can scan the layout for slots
    const container = document.createElement('div');
    comp.mount(container);

    const slotNames = comp.getSlotNames();

    // Assertions
    t.true(Array.isArray(slotNames), 'Result should be an array');
    t.is(slotNames.length, 3, 'Should find exactly 3 slots');
    t.true(slotNames.includes('sidebar'), 'Should contain "sidebar"');
    t.true(slotNames.includes('content'), 'Should contain "content"');
    t.true(slotNames.includes('footer'), 'Should contain "footer"');
});

test('Component: getSlotNames should return an empty array if no slots exist', t => {
    const comp = new Component();
    comp.setLayout('<div>No slots here</div>');

    comp.mount(document.createElement('div'));

    const slotNames = comp.getSlotNames();
    t.deepEqual(
        slotNames,
        [],
        'Should return an empty array when no data-slot attributes are present'
    );
});

test('Component: expand should warn if no parent element is stored', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');

    // Ensure parentElement is null and it's not a child of another component
    comp.$internals.parentElement = null;
    comp.$internals.parentComponent = null;

    // Trigger expand -> #resolveStandaloneTarget
    comp.expand();

    t.false(comp.isConnected, 'Component should not connect without parentElement');
});

test('Component: expand should warn if parent element is disconnected from DOM', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');

    const detachedEl = document.createElement('div');
    // We mount it to a detached element
    comp.mount(detachedEl);

    // Now we collapse it
    comp.collapse();

    // At this point detachedEl.isConnected is false. Trigger expand.
    comp.expand();

    t.false(comp.isConnected, 'Component should not expand into a disconnected DOM node');
});

test('Component: expand should warn if parent component is disconnected', t => {
    const parent = new Component();
    parent.setLayout('<div data-slot="main"></div>');
    // We don't mount parent, so parent.isConnected is false

    const child = new Component();
    child.setLayout('<span></span>');

    // Simulate being a child in a slot
    child.$internals.parentComponent = parent;
    child.$internals.assignedSlotName = 'main';

    // Trigger expand -> #resolveSlotTarget
    child.expand();

    t.false(child.isConnected, 'Child should not expand if parent is disconnected');
});

test('Component: expand should warn if slot name is not found in parent refs', t => {
    const container = document.createElement('div');
    const parent = new Component();
    parent.setLayout('<div data-slot="existingSlot"></div>');
    parent.mount(container);

    const child = new Component();
    child.setLayout('<span></span>');

    // Link to a non-existent slot name
    child.$internals.parentComponent = parent;
    child.$internals.assignedSlotName = 'wrongSlotName';

    // Trigger expand -> #resolveSlotTarget checks parent.$internals.scopeRefs['wrongSlotName']
    child.expand();

    t.false(
        child.isConnected,
        'Child should not expand if assigned slot is missing in parent layout'
    );
});

test('Component: #resolveSlotTarget should successfully return slotRef and mount child', t => {
    const container = document.createElement('div');
    document.body.appendChild(container);

    // 1. Setup connected parent
    class Parent extends Component {
        layout = '<div><div data-slot="targetSlot"></div></div>';
    }
    const parentComp = new Parent();
    parentComp.mount(container);

    // 2. Setup child and link it to the parent's slot
    const childComp = new Component();
    childComp.setLayout('<span>I am alive</span>');

    // Using the correct method we discussed earlier to ensure all internals are set
    parentComp.addToSlot('targetSlot', childComp);

    // 3. Manually collapse the child (without collapsing the parent)
    childComp.collapse();
    t.false(childComp.isConnected, 'Child should be disconnected after collapse');

    // 4. Act: Expand the child
    // This triggers: expand() -> #resolveSlotTarget -> returns slotRef -> mount()
    childComp.expand();

    // 5. Assertions
    const expectedSlot = parentComp.slotManager.getSlotElement('targetSlot');

    t.true(childComp.isConnected, 'Child should be connected again');
    t.is(
        childComp.getRootNode().parentElement,
        expectedSlot,
        '#resolveSlotTarget should have returned the correct slot element for mounting'
    );

    document.body.removeChild(container);
});

test('Component: $on should register event and return cleanup function', t => {
    const comp = new Component();
    const btn = document.createElement('button');
    let called = false;

    const originalAdd = btn.addEventListener;
    btn.addEventListener = (type, listener, options) => {
        t.truthy(options.signal, 'Component should pass a signal to addEventListener');
        originalAdd.call(btn, type, listener);
    };

    const remove = comp.$on(btn, 'click', () => {
        called = true;
    });

    btn.click();
    t.true(called, 'Handler should be called');

    btn.addEventListener = originalAdd;
});

test('Component: serialize should return an empty object by default', t => {
    const comp = new Component();
    const data = comp.serialize();

    t.is(typeof data, 'object', 'Should return an object');
    t.deepEqual(data, {}, 'Default serialization should be empty');
});

test('Component: subclasses should be able to override serialize', t => {
    class UserComp extends Component {
        serialize() {
            return { id: 1, name: 'Gemini' };
        }
    }
    const comp = new UserComp();
    t.deepEqual(comp.serialize(), { id: 1, name: 'Gemini' });
});

test('Component: hasRef and updateRefs should identify elements correctly', t => {
    class RefComp extends Component {
        layout = '<div><button data-ref="myBtn">Click</button></div>';
    }

    const container = document.createElement('div');
    const comp = new RefComp();
    comp.mount(container);

    t.true(comp.hasRef('myBtn'), 'Should find existing ref');
    t.false(comp.hasRef('nonExistent'), 'Should return false for missing ref');

    t.notThrows(() => comp.updateRefs(), 'Should update refs without error when connected');
});

test('Component: updateRefs should throw if component is not connected', t => {
    const comp = new Component();
    comp.setLayout('<div></div>');

    const error = t.throws(
        () => {
            comp.updateRefs();
        },
        { instanceOf: Error }
    );

    t.is(
        error.message,
        'Component is not connected to the DOM',
        'Should throw specific error message'
    );
});

test('Component: updateRefs should throw when refsAnnotation is violated', t => {
    class ValidatedComp extends Component {
        layout = '<div><input data-ref="requiredInput"></div>';
        refsAnnotation = {
            requiredInput: window.HTMLInputElement,
        };
    }

    const container = document.createElement('div');
    const comp = new ValidatedComp();
    comp.mount(container);

    t.notThrows(() => comp.updateRefs());

    comp.setLayout('<div>Empty</div>');
    comp.rerender();

    const error = t.throws(
        () => {
            comp.updateRefs();
        },
        { instanceOf: Error }
    );

    t.truthy(error, 'Validation must throw because the new root is empty');
});

test('Component: text update function should be set and executed', t => {
    const comp = new Component();
    let capturedInstance = null;

    comp.setTextUpdateFunction(instance => {
        capturedInstance = instance;
    });

    comp.reloadText();

    t.is(
        capturedInstance,
        comp,
        'reloadText should pass the component instance to the update function'
    );

    comp.setTextUpdateFunction(null);
    t.notThrows(
        () => comp.reloadText(),
        'reloadText should not throw if update function is not set'
    );
});

test('Component: setLayout should update layout and optionally refsAnnotation', t => {
    const comp = new Component();
    const newLayout = '<span>New</span>';
    const newAnnotation = { someRef: window.HTMLElement };

    comp.setLayout(newLayout);
    t.is(comp.layout, newLayout);
    t.is(comp.refsAnnotation, undefined, 'Annotation should remain undefined if not provided');

    comp.setLayout(newLayout, newAnnotation);
    t.is(comp.refsAnnotation, newAnnotation, 'Annotation should be updated');
});

test('Component: getRefs should throw if component is not connected', t => {
    const comp = new Component();
    comp.setLayout('<div data-ref="test"></div>');

    const error = t.throws(
        () => {
            comp.getRefs();
        },
        { instanceOf: Error }
    );

    t.is(error.message, 'Component is not connected to the DOM');

    const container = document.createElement('div');
    comp.mount(container);
    t.notThrows(() => comp.getRefs(), 'Should work when connected');

    comp.unmount();
    t.throws(() => comp.getRefs(), { instanceOf: Error }, 'Should throw again after unmount');
});

test('Component: should skip style injection if SSR styles are present', t => {
    // 1. Setup: Create a component class with styles
    class SsrComponent extends Component {
        static styles = '.ssr { color: red; }';
    }

    // 2. Mock SSR style tag in the document
    const styleTag = document.createElement('style');
    styleTag.id = 'ui-ssr-styles';
    document.head.appendChild(styleTag);

    const comp = new SsrComponent();
    comp.setLayout('<div></div>');
    const container = document.createElement('div');

    // 3. Act: Mounting triggers #ensureStylesInjected
    comp.mount(container);

    // 4. Assert
    t.true(SsrComponent._stylesInjected, 'Flag should be set to true');
    // We check that no NEW style tags were created (except our mock)
    const allStyles = document.querySelectorAll('style');
    t.is(allStyles.length, 1, 'Should not inject new styles if SSR styles exist');

    // Cleanup for other tests
    styleTag.remove();
    SsrComponent._stylesInjected = false;
});

test('Component: should inject static styles via adoptedStyleSheets (Mocked)', t => {
    class StyledComponent extends Component {
        static styles = '.test-adopted { color: green; }';
    }

    const mockSheet = { cssRules: [], replaceSync: () => {} };
    Config.window.document.adoptedStyleSheets = [];

    const originalCSSStyleSheet = Config.window.CSSStyleSheet;
    // @ts-ignore
    Config.window.CSSStyleSheet = class {
        constructor() {
            return mockSheet;
        }
    };

    const comp = new StyledComponent();
    comp.setLayout('<div></div>');
    StyledComponent._stylesInjected = false;

    // Act
    comp.mount(document.createElement('div'));

    // Assert
    t.true(StyledComponent._stylesInjected);
    t.true(
        // @ts-ignore
        Config.window.document.adoptedStyleSheets.includes(mockSheet),
        'Should add sheet to adoptedStyleSheets'
    );

    // Cleanup
    Config.window.CSSStyleSheet = originalCSSStyleSheet;
    delete Config.window.document.adoptedStyleSheets;
});

test('Component: should support hydration and skip style injection if SSR styles exist', t => {
    // 1. Setup: A component class with styles
    class HydratedComponent extends Component {
        static styles = '.hydrated { color: blue; }';
    }

    // Ensure state is clean for this specific test
    HydratedComponent._stylesInjected = false;

    // 2. Simulate SSR: add the style tag that the server would have generated
    const ssrStyleTag = document.createElement('style');
    ssrStyleTag.id = 'ui-ssr-styles';
    ssrStyleTag.textContent = '.hydrated { color: blue; }';
    document.head.appendChild(ssrStyleTag);

    const container = document.createElement('div');
    const comp = new HydratedComponent();
    comp.setLayout('<div></div>');
    // 3. Act: Mounting triggers #ensureStylesInjected()
    comp.mount(container);

    // 4. Assert
    t.true(HydratedComponent._stylesInjected, 'Flag must be set to true even if skip injection');

    // Verify that NO new styles were added to adoptedStyleSheets
    // (Assuming you've handled the JSDOM absence of adoptedStyleSheets as discussed before)
    if (Config.window.document.adoptedStyleSheets) {
        const hasAdopted = Config.window.document.adoptedStyleSheets.some(sheet =>
            Array.from(sheet.cssRules).some(rule => rule.cssText.includes('.hydrated'))
        );
        t.false(hasAdopted, 'Should NOT adopt new styles during hydration');
    }

    // Cleanup for other tests
    ssrStyleTag.remove();
    HydratedComponent._stylesInjected = false;
});

test('Component: final branch cleanup', t => {
    const comp = new Component();

    comp.unmount();
    comp.collapse();

    t.pass();
});
